INSERT INTO lenguaje (codigo, pais) VALUES (  "AF" , "Afghanistan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AX" , "Aland Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AL" , "Albania");
INSERT INTO lenguaje (codigo, pais) VALUES (  "DZ" , "Algeria");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AS" , "American Samoa");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AD" , "Andorra");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AO" , "Angola");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AI" , "Anguilla");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AQ" , "Antarctica");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AG" , "Antigua and Barbuda");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AR" , "Argentina");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AM" , "Armenia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AW" , "Aruba");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AU" , "Australia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AT" , "Austria");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AZ" , "Azerbaijan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BS" , "Bahamas the");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BH" , "Bahrain");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BD" , "Bangladesh");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BB" , "Barbados");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BY" , "Belarus");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BE" , "Belgium");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BZ" , "Belize");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BJ" , "Benin");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BM" , "Bermuda");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BT" , "Bhutan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BO" , "Bolivia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BA" , "Bosnia and Herzegovina");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BW" , "Botswana");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BV" , "Bouvet Island (Bouvetoya)");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BR" , "Brazil");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IO" , "British Indian Ocean Territory (Chagos Archipelago)");
INSERT INTO lenguaje (codigo, pais) VALUES (  "VG" , "British Virgin Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BN" , "Brunei Darussalam");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BG" , "Bulgaria");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BF" , "Burkina Faso");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BI" , "Burundi");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KH" , "Cambodia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CM" , "Cameroon");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CA" , "Canada");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CV" , "Cape Verde");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KY" , "Cayman Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CF" , "Central African Republic");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TD" , "Chad");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CL" , "Chile");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CN" , "China");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CX" , "Christmas Island");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CC" , "Cocos (Keeling) Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CO" , "Colombia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KM" , "Comoros the");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CD" , "Congo");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CG" , "Congo the");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CK" , "Cook Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CR" , "Costa Rica");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CI" , "Cote d\"Ivoire");
INSERT INTO lenguaje (codigo, pais) VALUES (  "HR" , "Croatia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CU" , "Cuba");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CY" , "Cyprus");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CZ" , "Czech Republic");
INSERT INTO lenguaje (codigo, pais) VALUES (  "DK" , "Denmark");
INSERT INTO lenguaje (codigo, pais) VALUES (  "DJ" , "Djibouti");
INSERT INTO lenguaje (codigo, pais) VALUES (  "DM" , "Dominica");
INSERT INTO lenguaje (codigo, pais) VALUES (  "DO" , "Dominican Republic");
INSERT INTO lenguaje (codigo, pais) VALUES (  "EC" , "Ecuador");
INSERT INTO lenguaje (codigo, pais) VALUES (  "EG" , "Egypt");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SV" , "El Salvador");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GQ" , "Equatorial Guinea");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ER" , "Eritrea");
INSERT INTO lenguaje (codigo, pais) VALUES (  "EE" , "Estonia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ET" , "Ethiopia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "FO" , "Faroe Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "FK" , "Falkland Islands (Malvinas)");
INSERT INTO lenguaje (codigo, pais) VALUES (  "FJ" , "Fiji the Fiji Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "FI" , "Finland");
INSERT INTO lenguaje (codigo, pais) VALUES (  "FR" , "France French Republic");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GF" , "French Guiana");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PF" , "French Polynesia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TF" , "French Southern Territories");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GA" , "Gabon");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GM" , "Gambia the");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GE" , "Georgia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "DE" , "Germany");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GH" , "Ghana");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GI" , "Gibraltar");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GR" , "Greece");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GL" , "Greenland");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GD" , "Grenada");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GP" , "Guadeloupe");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GU" , "Guam");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GT" , "Guatemala");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GG" , "Guernsey");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GN" , "Guinea");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GW" , "Guinea-Bissau");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GY" , "Guyana");
INSERT INTO lenguaje (codigo, pais) VALUES (  "HT" , "Haiti");
INSERT INTO lenguaje (codigo, pais) VALUES (  "HM" , "Heard Island and McDonald Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "VA" , "Holy See (Vatican City State)");
INSERT INTO lenguaje (codigo, pais) VALUES (  "HN" , "Honduras");
INSERT INTO lenguaje (codigo, pais) VALUES (  "HK" , "Hong Kong");
INSERT INTO lenguaje (codigo, pais) VALUES (  "HU" , "Hungary");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IS" , "Iceland");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IN" , "India");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ID" , "Indonesia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IR" , "Iran");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IQ" , "Iraq");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IE" , "Ireland");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IM" , "Isle of Man");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IL" , "Israel");
INSERT INTO lenguaje (codigo, pais) VALUES (  "IT" , "Italy");
INSERT INTO lenguaje (codigo, pais) VALUES (  "JM" , "Jamaica");
INSERT INTO lenguaje (codigo, pais) VALUES (  "JP" , "Japan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "JE" , "Jersey");
INSERT INTO lenguaje (codigo, pais) VALUES (  "JO" , "Jordan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KZ" , "Kazakhstan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KE" , "Kenya");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KI" , "Kiribati");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KP" , "Korea");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KR" , "Korea");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KW" , "Kuwait");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KG" , "Kyrgyz Republic");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LA" , "Lao");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LV" , "Latvia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LB" , "Lebanon");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LS" , "Lesotho");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LR" , "Liberia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LY" , "Libyan Arab Jamahiriya");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LI" , "Liechtenstein");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LT" , "Lithuania");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LU" , "Luxembourg");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MO" , "Macao");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MK" , "Macedonia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MG" , "Madagascar");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MW" , "Malawi");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MY" , "Malaysia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MV" , "Maldives");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ML" , "Mali");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MT" , "Malta");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MH" , "Marshall Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MQ" , "Martinique");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MR" , "Mauritania");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MU" , "Mauritius");
INSERT INTO lenguaje (codigo, pais) VALUES (  "YT" , "Mayotte");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MX" , "Mexico");
INSERT INTO lenguaje (codigo, pais) VALUES (  "FM" , "Micronesia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MD" , "Moldova");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MC" , "Monaco");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MN" , "Mongolia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ME" , "Montenegro");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MS" , "Montserrat");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MA" , "Morocco");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MZ" , "Mozambique");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MM" , "Myanmar");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NA" , "Namibia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NR" , "Nauru");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NP" , "Nepal");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AN" , "Netherlands Antilles");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NL" , "Netherlands the");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NC" , "New Caledonia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NZ" , "New Zealand");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NI" , "Nicaragua");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NE" , "Niger");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NG" , "Nigeria");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NU" , "Niue");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NF" , "Norfolk Island");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MP" , "Northern Mariana Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "NO" , "Norway");
INSERT INTO lenguaje (codigo, pais) VALUES (  "OM" , "Oman");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PK" , "Pakistan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PW" , "Palau");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PS" , "Palestinian Territory");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PA" , "Panama");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PG" , "Papua New Guinea");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PY" , "Paraguay");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PE" , "Peru");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PH" , "Philippines");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PN" , "Pitcairn Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PL" , "Poland");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PT" , "Portugal Portuguese Republic");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PR" , "Puerto Rico");
INSERT INTO lenguaje (codigo, pais) VALUES (  "QA" , "Qatar");
INSERT INTO lenguaje (codigo, pais) VALUES (  "RE" , "Reunion");
INSERT INTO lenguaje (codigo, pais) VALUES (  "RO" , "Romania");
INSERT INTO lenguaje (codigo, pais) VALUES (  "RU" , "Russian Federation");
INSERT INTO lenguaje (codigo, pais) VALUES (  "RW" , "Rwanda");
INSERT INTO lenguaje (codigo, pais) VALUES (  "BL" , "Saint Barthelemy");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SH" , "Saint Helena");
INSERT INTO lenguaje (codigo, pais) VALUES (  "KN" , "Saint Kitts and Nevis");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LC" , "Saint Lucia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "MF" , "Saint Martin");
INSERT INTO lenguaje (codigo, pais) VALUES (  "PM" , "Saint Pierre and Miquelon");
INSERT INTO lenguaje (codigo, pais) VALUES (  "VC" , "Saint Vincent and the Grenadines");
INSERT INTO lenguaje (codigo, pais) VALUES (  "WS" , "Samoa");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SM" , "San Marino");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ST" , "Sao Tome and Principe");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SA" , "Saudi Arabia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SN" , "Senegal");
INSERT INTO lenguaje (codigo, pais) VALUES (  "RS" , "Serbia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SC" , "Seychelles");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SL" , "Sierra Leone");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SG" , "Singapore");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SK" , "Slovakia (Slovak Republic)");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SI" , "Slovenia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SB" , "Solomon Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SO" , "Somalia Somali Republic");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ZA" , "South Africa");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GS" , "South Georgia and the South Sandwich Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ES" , "Spain");
INSERT INTO lenguaje (codigo, pais) VALUES (  "LK" , "Sri Lanka");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SD" , "Sudan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SR" , "Suriname");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SJ" , "Svalbard & Jan Mayen Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SZ" , "Swaziland");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SE" , "Sweden");
INSERT INTO lenguaje (codigo, pais) VALUES (  "CH" , "Switzerland Swiss Confederation");
INSERT INTO lenguaje (codigo, pais) VALUES (  "SY" , "Syrian Arab Republic");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TW" , "Taiwan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TJ" , "Tajikistan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TZ" , "Tanzania");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TH" , "Thailand");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TL" , "Timor-Leste");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TG" , "Togo");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TK" , "Tokelau");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TO" , "Tonga");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TT" , "Trinidad and Tobago");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TN" , "Tunisia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TR" , "Turkey");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TM" , "Turkmenistan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TC" , "Turks and Caicos Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "TV" , "Tuvalu");
INSERT INTO lenguaje (codigo, pais) VALUES (  "UG" , "Uganda");
INSERT INTO lenguaje (codigo, pais) VALUES (  "UA" , "Ukraine");
INSERT INTO lenguaje (codigo, pais) VALUES (  "AE" , "United Arab Emirates");
INSERT INTO lenguaje (codigo, pais) VALUES (  "GB" , "United Kingdom");
INSERT INTO lenguaje (codigo, pais) VALUES (  "UK" , "United Kingdom");
INSERT INTO lenguaje (codigo, pais) VALUES (  "US" , "United States of America");
INSERT INTO lenguaje (codigo, pais) VALUES (  "UM" , "United States Minor Outlying Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "VI" , "United States Virgin Islands");
INSERT INTO lenguaje (codigo, pais) VALUES (  "UY" , "Uruguay Eastern Republic of");
INSERT INTO lenguaje (codigo, pais) VALUES (  "UZ" , "Uzbekistan");
INSERT INTO lenguaje (codigo, pais) VALUES (  "VU" , "Vanuatu");
INSERT INTO lenguaje (codigo, pais) VALUES (  "VE" , "Venezuela");
INSERT INTO lenguaje (codigo, pais) VALUES (  "VN" , "Vietnam");
INSERT INTO lenguaje (codigo, pais) VALUES (  "WF" , "Wallis and Futuna");
INSERT INTO lenguaje (codigo, pais) VALUES (  "EH" , "Western Sahara");
INSERT INTO lenguaje (codigo, pais) VALUES (  "YE" , "Yemen");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ZM" , "Zambia");
INSERT INTO lenguaje (codigo, pais) VALUES (  "ZW" , "Zimbabwe");
